### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by sohilpandya** [InFact-coop/building-exploratory#31]
@emilyb7 mentioned a lot of great points and some of them are still remaining in #24. 

We need to tackle these at a later date to clean things up. 

# Could Do
- Using react router

# Todo 
- [ ] BuildingCard there is some repetition, we need to create some smaller components
- [x] fact  = 'N/A'
- [ ] alt text should be `building_name` on image tags
- [ ] Markers.js - move repeated variables / functions
